#!/usr/bin/env sh

preview() {
	cat <<-EOF | paste -sd '' >"$FIFO_UEBERZUG"
	{
	"action": "add", "identifier": "lf-preview",
	"path": "$1", "x": $4, "y": $5, "width": $2, "height": $3,
	"scaler": "contain"
	}
	EOF
}

file="$1"; shift
case "$(basename "$file" | tr '[:upper:]' '[:lower:]')" in
    *.tar*) tar tf "$file" ;;
    *.zip) unzip -l "$file" ;;
    *.rar) unrar l "$file" ;;
    *.7z) 7z l "$file" ;;
    *.avi|*.mp4|*.mkv)
        thumbnail="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumbnail.png"
        ffmpeg -y -i "$file" -vframes 1 "$thumbnail"
        preview "$thumbnail" "$@"
        ;;
    *.pdf)
        thumbnail="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumbnail.png"
        gs -o "$thumbnail" -sDEVICE=pngalpha -dLastPage=1 "$file" >/dev/null
        preview "$thumbnail" "$@"
        ;;
    *.jpg|*.jpeg|*.png|*.bmp)
        preview "$file" "$@" ;;
    *.svg)
        thumbnail="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumbnail.png"
        gm convert "$file" "$thumbnail"
        preview "$thumbnail" "$@"
        ;;
    *.gif)
        thumbnail="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumbnail.png"
        gm convert "$file[0]" "$thumbnail"
        preview "$thumbnail" "$@"
        ;;
    *) bat --terminal-width -1 -f "$file" ;;
esac

exit 1
