#!/usr/bin/env sh

preview() {
	cat <<-EOF | paste -sd '' > "$FIFO_UEBERZUG"
	{
	"action": "add", "identifier": "lf-preview",
	"path": "$1", "x": $4, "y": $5, "width": $2, "height": $3,
	"scaler": "contain"
	}
	EOF
}

file="$1"; shift
case "$(file --dereference --brief --mime-type -- "$file")" in
    *.tar*) tar tf "$file" ;;
    *.zip) unzip -l "$file" ;;
    *.rar) unrar l "$file" ;;
    *.7z) 7z l "$file" ;;
    video/*)
        thumbnail="${XDG_CACHE_HOME}/lf/thumbnail.png"
        ffmpeg -y -i "$file" -vframes 1 "$thumbnail"
        preview "$thumbnail" "$@"
        ;;
    *.pdf)
        thumbnail="${XDG_CACHE_HOME}/lf/thumbnail.png"
        gs -o "$thumbnail" -sDEVICE=pngalpha -dLastPage=1 "$file" >/dev/null
        preview "$thumbnail" "$@"
        ;;
    *.svg)
        thumbnail="${XDG_CACHE_HOME}/lf/thumbnail.png"
        gm convert "$file" "$thumbnail"
        preview "$thumbnail" "$@"
        ;;
    *.gif)
        thumbnail="${XDG_CACHE_HOME}/lf/thumbnail.png"
        gm convert "$file[0]" "$thumbnail"
        preview "$thumbnail" "$@"
        ;;
    image/*) preview "$file" "$@" ;;
    text/html) w3m -dump "$file" ;;
    text/*|application/json) bat --terminal-width $(($3-2)) -f "$file" ;;
    *) exiftool "$file" ;;
esac

exit 1
