#!/usr/bin/env sh

case "$(file --dereference --brief --mime-type -- "$1")" in
    application/gzip)
        tar tf "$1" ;;
    application/zip)
        unzip -l "$1" ;;
    application/vnd.rar)
        unrar l "$1" ;;
    application/x-7z-compressed)
        7z l "$1" ;;
    text/* | application/json | application/javascript | image/svg+xml)
        bat --terminal-width $(($3-2)) -f "$1" ;;
    *)
        exiftool $1 ;;
esac
